SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `OMS_ORDER_1`;
CREATE TABLE `OMS_ORDER_1` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APPLY_DATE` datetime NOT NULL COMMENT '分区键',
  `CUST_NO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '客户号',
  `ORDER_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单号',
  `LINE_NO` int NOT NULL COMMENT '交易文件行号',
  `LINE_RECORD` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '交易文件记录',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`,`APPLY_DATE`) USING BTREE,
  UNIQUE KEY `IDX_BIZ_PK` (`CUST_NO`,`ORDER_ID`),
  KEY `IDX_LINE_NO` (`LINE_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=10001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单交易表';

DROP TABLE IF EXISTS `OMS_ORDER_2`;
CREATE TABLE `OMS_ORDER_2` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APPLY_DATE` datetime NOT NULL COMMENT '分区键',
  `CUST_NO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '客户号',
  `ORDER_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单号',
  `LINE_NO` int NOT NULL COMMENT '交易文件行号',
  `LINE_RECORD` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '交易文件记录',
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`,`APPLY_DATE`) USING BTREE,
  UNIQUE KEY `IDX_BIZ_PK` (`CUST_NO`,`ORDER_ID`),
  KEY `IDX_LINE_NO` (`LINE_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=10001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单交易表';

SET FOREIGN_KEY_CHECKS = 1;